### ISSUE TITLE
Z-wave: Update of device settings not possible (Fibaro motion sensor z-wave+)

### ISSUE THREAD

**Issue by Gand41f** [athombv/homey#1145]
**What is your Homey version (Settings → System)?**

1.0.3 (Homey itself)
1.1.1 (Fibaro app)

**What did you try to achieve?**

I tried to change the settings of my Fibaro Motion Sensor (z-wave plus version). For example I wanted to switch off the LED. I applied the settings and Homey showed it would transfer the settings on the next wakeup of the device. Then I manually woke up the sensor by pressing its button. When pressing the "save" button again. Homey claims that the settings have been updated.

**What was the result?**

No settings were changed. The LED is still on.

**What did you expect as result?**

That the sensor changed its settings.

**Any other remarks**

This used to work in an earlier version. I think 1.0.1, but I am not sure.

**Comment by bvdbos** [comment]
Better report this to https://github.com/athombv/com.fibaro/issues ?

**Comment by caseda** [comment]
He can report it here as well since it's not an app problem. 
Please try following these steps :

Reboot your homey,

Then go to homey's settings into z-wave menu item and open stuff for geeks
So you can see when zwave is done loading everything (commands get empty) 

Then change the LED color to something else if the color you want is still selected and press save afterwards (no need to wakeup your device in this step) 
Then change the color, wakeup your device and only then press save, and it should have saved it properly :+1:

Why do cumbersome?
Zwave can still hang, and homey still has problems knowing if the device is awake ready to receive parameters, or just "awake"  to send small data
Both should be better/fixed in the next homey update
Hopefully

**Comment by Gand41f** [comment]
@caseda 
Okay, this worked, but after this I couldn't change the settings again. So I have to reboot Homey everytime I want to change a setting right now?

**Comment by caseda** [comment]
the reboot was just to make sure the chip is not stuck, you can see this by looking in the settings -> z-wave and then open stuff for geeks.

+ if the commands are empty, you are good to go.
+ If the status says "processSendCommand"
wait for a few seconds and see if it blinks shortly once in a while, then you can just wait until it is done processing all data. (this should be better in next update)
It should not matter if you save the parameters anyway, but there is a possibility the sensor is going asleep again while sending the parameters.
+ If it does not blink for at least _35 seconds_ then your chip is stuck and you will need to reboot (also should be fixed in next update)

the most important when saving settings at this moment, is that it is close by homey, and awake just before you press the save button.
then it should work just ok, every time

**Comment by jaimevisser** [comment]
Related: https://github.com/athombv/com.fibaro/issues/96

**Comment by Gand41f** [comment]
What I tried today: When I was at work this morning(so nobody was home, who could trigger the sensors), I changed the settings of sensors. When I came home in the evening none of my 5 sensor had accepted the new seetings.

**Comment by caseda** [comment]
@G4nd41f it is not only on motion that the device "wakes up" but on anything it sends like lux and temperature also

Just wait until it is fixed in 1.1.4 (the next homey update)

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not in Homey version 1.1.4?

**Comment by Gand41f** [comment]
In version 1.1.4, Homey keeps telling me that the settings will be applied on the next wake up of the device despite I did wake up the sensor manually 20cm away from Homey. Will it maybe transmit the settings after the 2 hour wakeup intervall?

**Comment by caseda** [comment]
@gand4lf
Did you change the value(s) of the settings you wanted to change everytime you press the save button? It will only send the value of settings that are a different value from last save.

**Comment by Gand41f** [comment]
Yes, I did. However Homey does not apply the settings to the sensor. Also not after waiting a whole day. In the last version Homey claimed to have changed the settings, now it keeps telling me that it will do so at the next wakeup of the device and still does nothing.

**Comment by caseda** [comment]
@Gand41f please try re-pairing it, it probably included faulty (half, athom calls it) in a previous homey firmware

**Comment by Gand41f** [comment]
I did re-pair it and it still does not work. Same symptoms as in my previous post.

**Comment by Gand41f** [comment]
With Fibaro 1.2.2. this issue almost seems to be resolved. I could update the settings of all of my 5 motion sensors. However, this took me more than 1 hour in total, because some of the sensors had to be re-paired before it worked.

**Comment by RobinBol** [comment]
@Gand41f thanks for letting us know, do you agree we can close this issue now? If you have any further issues please re-open this issue or create a new one!
