### ISSUE TITLE
Aeotec Smart Dimmer 6 ZW099 / Smartswitch 6 EZW096 not showing Energy consumption

### ISSUE THREAD

**Issue by Tvandongen** [athombv/homey#1212]
**What is your Homey version (Settings → System)?**

1.0.1.2

**What did you try to achieve?**

I Bought 2 Smart Dimmer 6 Aeotec ZW099 and installed the Aeotec app. I can see the devices and switch them on/off (including dimming option). 
Also bought an Smartswitch 6 EZW096. This device I can also switch on / off

**What was the result?**

For all devices the power consumption is not shown in the devices / insight

**What did you expect as result?**

Show the power consumption the same way as the fibaro dimmer 2

**Any other remarks**

**Comment by djeskoswe** [comment]
Same on AEO_ZW075,  no energy reading

**Comment by caseda** [comment]
You guys probably included your device as a socket with a light attached am I right?

You can get the wattage and kWh of you include your socket as a "other device attached" socket.

Or you will have to wait until someone (like the assigned developer) has added the custom mobile card to the driver.

**Comment by djeskoswe** [comment]
Added as other device attached,  just a - shows

**Comment by RobinBol** [comment]
Fixed this for ZW099 in latest aeotec app update. For the Dimmer i'd recommend to re-pair, I tried it here and it works!

**Comment by djeskoswe** [comment]
No reading on AEO_ZW075

**Comment by RobinBol** [comment]
Ok, but this issue is related to ZW099/96 if you have issues with another device please create a separate issue here https://github.com/athombv/com.aeotec/issues

**Comment by djeskoswe** [comment]
Ok

**Comment by Tvandongen** [comment]
Unfortunately I do not get it to work. I have updated the APP to v1.26, removed both the ZW099 and restarted homey. After that I added 1 ZW099 but this device still does not showing energy consumption. Checked it with Devices, Insgihts and tags (flows).
Did not test the ZW096.

**Comment by RobinBol** [comment]
Are you able to run the app in debug mode and post the logging?

Try to switch the device to force a power load change.

**Comment by Tvandongen** [comment]
I can run it in debug mode if hou can inform me how to start it.
Op wo 4 jan. 2017 om 23:26 schreef Robin Bolscher <notifications@github.com>

**Comment by Tvandongen** [comment]
I have followed the instructions and got the follwing information
? Select active Homey: Homey @ xxx.xxx.xxx.xxx80
1/4 - Archiving...
2/4 - Uploading to Homey @ xxx.xxx.xxx.xxx:80...
3/4 - Running `com.aeotec`, press CTRL+C to abort...
4/4 - Debugging...

-------------------------------------------------
com.aeotec running...
-------------------------------------------------

Stopping...
App uninstalled

While the app was running in debug mode I have removed the ZW099 and did re-pair. 
However I cannot find the debug log.
Where can I find this ?

**Comment by caseda** [comment]
add the debug tag just above capabilities:
```
module.exports = new ZwaveDriver(path.basename(__dirname), {
	debug: true,
	capabilities: {
```

**Comment by Tvandongen** [comment]
I have attached the results for removing and re-pair the ZW099
In the logging I see some time out issues. The Homey is about 10 cm from the ZW099, so distance should not be the cause of the time-outs.

[ZW099 debug logging.txt](https://github.com/athombv/homey/files/687864/ZW099.debug.logging.txt)

**Comment by caseda** [comment]
the timeout issues are not on the measuring part though, they are perfectly fine coming on in your homey.
even though a little weird precision level (3).

Maybe this needs to be forced in the parser to precision level 2 @RobinBol?
like the capability itself is using.

can't think of an other reason.

try pulling the plug for a few minutes, maybe that also fixes it inside homey itself.

**Comment by Tvandongen** [comment]
Pulled the plug on both Homey and the ZW099 for about 1 hour. Didn't make any difference.

**Comment by RobinBol** [comment]
Very strange, the reports are coming in, the realtime events should emit (even though the precision is not the same as the capability's). The precision is 3 here as well, and it works.

@Tvandongen if you open the device mobile card, and manually switch the Dimmer/Switch on/off do you see this change reflected in the mobile card (greying out)?

**Comment by Tvandongen** [comment]
@RobinBol  If I open the device mobile card the light will be switched on/off. The card is also greyed out if not selected.

**Comment by RobinBol** [comment]
@Tvandongen I found a bug that might be causing the issue for the ZW099, fixed that in the Aeotec app update I just released; will therefore close this issue. If you have further problems please let us know!
