### ISSUE TITLE
Somfy RTS rollershutters aint pairing.

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#145]
they should , they are also paired with the RfxTrx from rfxcom.

**Comment by Dennishacq** [comment]
Hi @nattlip 
Thank you for reporting this issue.
Does unplugging Homey and plugging him back in solve this problem?

**Comment by nattlip** [comment]
no nor rebooting.

**Comment by Jurgen0000** [comment]
I have a problem too with RTS. Putting RTS in learn mode (using Somfy remote.. shutters move up and down .. seen by Homey... but next step (Homey sending up an down) .. is not working.. Homey sees it as a device but can't control any RTS. Working fine with normal remotes from Somfy and also with Homewizard.

**Comment by nattlip** [comment]
i see on the forum a distance problem could be the isssue.

https://forum.athom.com/discussion/737/poor-range-somfy-rts

**Comment by jcastrol07** [comment]
I also have the same/similar  problem ..I paired 3 somfy blinds, I got to action one of them once and after that it stopped working
I can see the devices but the buttons are now greyed out
I also tried to disable and enable again somfy app but no luck
Any advice on workarounds are welcome

**Comment by Dennishacq** [comment]
@jcastrol07 This problem should be fixed in Somfy v1.0.7

**Comment by nattlip** [comment]
which is available in app store now.

**Comment by nattlip** [comment]
my somfy rollershutters aint pairing yet with v1.0.7

**Comment by ReinierH** [comment]
@nattlip 
The app doesn't fix the pairing issue. The fix will be patched in 0.8.19

**Comment by nattlip** [comment]
somfy rollershutterpairing works with 0.8.20.
