### ISSUE TITLE
Mouse-down event "hangs" on choosing Hue/Sat/Temp on Philips Hue (bug) [0.8.17]

### ISSUE THREAD

**Issue by athomey** [athombv/homey#164]
Reproduction: Add a Hue (not Lux) in devices | Mouse-left-click-down on the choosing-part of Hue/Sat/Temp | Move mouse outside the pop-up dialog | Release-mouse-left-click >> From now on **the mouse/scrolling of the options is "stuck" until you click again, this is wrong**. Also, this behaviour is DIFFERENT then when you do the same, but stay inside the Hue dialog.

![image](https://cloud.githubusercontent.com/assets/16608801/13019107/ab9275ca-d1cd-11e5-9f4f-9f69ff82e008.png)

**Comment by WeeJeWel** [comment]
Should be fixed ages ago :-)

**Comment by jeroenvollenbrock** [comment]
*And reintroduced with components rewrite

**Comment by bvdbos** [comment]
Does this still happen?

**Comment by athomey** [comment]
Cannot confirm at the moment. Everything is down here with Homey, and lack of time. I can re-open if problem is still there? Or someone else has to confirm.

**Comment by bvdbos** [comment]
closeme?

**Comment by athomey** [comment]
Still down. I suggest we close the ticket, until me or someone refiles if it is still an issue. It's so long ago, I assume it must be fixed by now. If not by you, then by library updates of GUI elements you use.
