### ISSUE TITLE
Homey stalls on boot on 1.5.0.-rc2 with red or steady orange ring

### ISSUE THREAD

**Issue by jghaanstra** [athombv/homey#1731]
**What is your Homey version (Settings → System)?**
1.5.0-rc2

**What did you try to achieve?**
Reboot Homey to because of voice recognition not working or apps randomly crashing.

**Please include detailed steps how we can reproduce the issue**
Use the reboot Homey function onder "Settings > System".

**What was the result?**
Homey reboots but during the reboot sequence it stalls with a red or steady orange LED ring. This takes up a minute or two and after that it continues to boot normally. Something in the boot process is not going smoothly.

**What did you expect as result?**
Homey rebooting smoothly within a couple of minutes

**Please attach a Homey System log (Settings -> System -> Send Log)**
A3CF34F988

**Comment by philsniff** [comment]
i can underline this. booting (ptp or just reboot) takes way longer then before and it comes to a orange freeze of the led! it stops spinning for 5-10 minutes and then goes on. 
from then it is just 2 minutes to the end of the reboot.

**Comment by JPe2** [comment]
Same on my Homey, it takes very long, just when you think it's definitively "hanging", it is starting up.

**Comment by mruiter** [comment]
The bug is under fixing by Athom.

**Comment by JPe2** [comment]
Homey Firmware Versie: 1.5.0-rc.4
just tried a reset via the menu, after 2 minutes circling orange, the circling stops for 5 minutes, then it starts circling again for 2 minutes and the rainbow is back again, so you only have to be patient for 10 minutes.

**Comment by jeroenvollenbrock** [comment]
Hopefully fixed in rc5

**Comment by JPe2** [comment]
Homey Firmware Versie: 1.5.0-rc.5  restart is now reduced to 3 minutes

**Comment by jeroenvollenbrock** [comment]
Did the ledring freezes stop as well?

**Comment by JPe2** [comment]
the orange circling stopped after appr. 2 min. freezes for less then a minute. I did not time it exactly.

**Comment by jghaanstra** [comment]
This issue was never about the total reboot time, it takes some time but this has always been the case and it builds up as more features are added with newer firmwares (like ZigBee). It's not a big deal to me.

I was worried about the freezing led ring though as it gives you the idea the boot process is killed and your Homey just died on you. On 1.5.0-rc5 this freezing still occurs on my Homey but has been reduced to about 10 seconds.

**Comment by bvdbos** [comment]
10 seconds, then this can be closed or do you still have this @JPe2 ?

**Comment by jghaanstra** [comment]
I do not experience this anymore on 1.5.0-RC6. Issue closed.
