### ISSUE TITLE
WiFi setup doesn't use selected network when hidden is filled in

### ISSUE THREAD

**Issue by RobertMe** [athombv/homey#2337]
**Metadata**

* **Homey Version**: 1.5.8 (although I guess irrelevant as it's in the setup/recovery)
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
(Re)connecting Homey to my wifi network.
1. Entered the setup
2. On the select network/SSID page filled in a hidden SSID name
3. (Homey couldn't connect to this network so) went back to select network/SSID page
4. Selected a different (listed, non hidden) SSID
5. Filled in the password and continued

**What did you expect as result?**
Homey would connect just fine to this (second) network.

**What was the result?**
Homey didn't connect, after some time (with blue LED) it said that if failed to connect to the network

**Any other remarks**
After I emptied the hidden SSID field it could connect just fine. So it seems like filling in a hidden SSID name always overrules the selected SSID, even when selecting an SSID later then you entered the hidden SSID name.
IMO there are two possibilities to fix this:
1. Automatically clear the hidden SSID name field when selecting a network from the list
2. Add a "hidden" option to the list (possibly hiding the SSID name field while not selected) so the setup page knows if it should connect to the given SSID name or one from the the list

**Comment by Dijker** [comment]
I guess you bought a new Homey? 
Tis was an Issue in 1.5.6 as you got from Factory.
Should be fixed in 1.5.8 that is installed after configuring the Wifi ;-)

See #2142 
Can you try to do a a recovery and connect to the Hidden Network?
https://www.athom.com/ondersteuning/KB000026/

**Comment by RobertMe** [comment]
Nope, came from 1.5.3. But my issue isn't with that it couldn't connect to the hidden network anymore, but with the fact that during the setup after I was unable to connect to the hidden network, but than selecting a different network it was (I think) still trying to connect to the hidden network.

So even after selecting a network from the list, it still tried to connect to the hidden network (as a name was filled in). So my issue is about the user experience/bug that the hidden SSID name always overrules the selected SSID name from the list. Not with the fact that the Homey didn't connect to the hidden network.

But if my original issue indeed was with that my Homey couldn't connect to the hidden network, then that means that #2142 isn't fully fixed. (Although that ticket does state that the connection is lost immediately after making the network hidden again, while for me it still works fine after I made the network hidden again).

**Comment by Dijker** [comment]
Ahhh Sorry, Maybe I Was to Quick but Nice to see a good clarification! 
Good one for @ jeroenvollenbrock I think! 
Up to a better User Experience.....

**Comment by rkokkelk** [comment]
After some more testing in the past few days, using 1.5.8. I still have issues that Homey does not connect properly to hidden networks. 

As mentioned above I also have problems with connecting to hidden networks. Furthermore, once a normal network is changed to hidden, Homey also fails to reconnect to it. So issue #2142, is not fixed yet.

**Comment by RobertMe** [comment]
As I already mentioned, this ticket is _not_ about Homey not being able to connect to a hidden network, nor that it looses the connection to a hidden network. I created this solely because of the user experience issue that during the setup you can't go back, select a network from the list, and connect to it (as you also need to (manually) clear the "Hidden SSID name" field).
