### ISSUE TITLE
[nl.klikaanklikuit] device AWST-8802 not working

### ISSUE THREAD

**Issue by LithiumNL** [athombv/homey#2440]
**Metadata**

* **Homey Version**: 1.5.9
* **Homey Log Code**: 
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**: 3.1.5
* **Homey App Log Code**: ccca1f1b-2636-4a29-8d98-89f4358fced6
* **Affected Devices (preferably product codes)**: AWST-8802

**What did you try to achieve?**
I tried to let a light switch on and off when pressing one of the buttons.

**What did you expect as result?**
One of the lights would go on or off.

**What was the result?**
No response from the light.

**Any other remarks**
Added the device and notice that in the pairing mode I could not see what button I was pressing. I was able to see a good result when adding its brother (AWST-8800).
Made a flow and set when 8802 was pressed the lights should go on or off. This didn't worked. Did the same with the 8800 and it worked.
Signals are coming in because I can pair the device and Homey Logger shows me the log lines when pressing the buttons.

**Comment by BasKiers** [comment]
Hi,

Thanks for reporting your issue.
This is a known issue and we are currenlty QA testing a new version of the KlikAanKlikUit which fixes this. Thus this issue should be resolved in the next update of the KlikAanKlikUit app.

Regards,
Bas

**Comment by LithiumNL** [comment]
Hi Bas,

Thanks for your reply!. Do you have any insight when the release is planned to be rolled out?

**Comment by LithiumNL** [comment]
Hi Bas,

Thanks for your reply!. Do you have any insight when the release is planned to be rolled out?

**Comment by Bastijn** [comment]
Hi all. This thread is more than 2 months old, but the problem is still there. Any update?

**Comment by lubbertkramer** [comment]
Bas has left Athom month ago so that could explain the delay, its maybe better to contact support@athom.com because they maybe have overlooked this issue as it's assigned to Bas

**Comment by Bastijn** [comment]
Thanks for the reply. I will contact support then.

**Comment by DieterKoblenz** [comment]
Problem still exists after the updates.

**Comment by DieterKoblenz** [comment]
Solved in at least v4.0.3.

**Comment by KyleAthom** [comment]
Solved in version 4.0.7 stable.
