### ISSUE TITLE
Z-Wave Include homey in another network

### ISSUE THREAD

**Issue by sebohans** [athombv/homey#856]
**What is your Homey version (Settings → System)?**

0.9.3

I'm trying to add Homey as a secondary controller to my Homeseer setup.
On my homeseer device I trigger the "send network information to another controller" 
On my homey I press the "Include homey in another network button"
After this there is a new node created in Homeseer.
And i get an error message that the security negotiation failed.
See homeseer log below.

_### "Replicate Send started...
Activate the "Receive" function on the other controller while it is close to your HomeSeer interface...
A new node is being added...
Adding a new CONTROLLER...
DONE - Replication Send Operation is Complete.
Done. Node 55 Added. 
Reloading (importing) node information...
Synchronizing node information with HomeSeer and creating new device(s) as necessary...
Synchronize nodes finished. Number of device nodes to be created/added = 1
Negotiating or Verifying SECURITY SCHEME for node 55
Warning: Failed to get a SECURITY SCHEME or verify the key from node 55. Device may not be added properly to HomeSeer.
Warning: The security device may have a timeout when adding to the network, bring the device close to HomeSeer and use the Add Node button to add it (remove it first)
Warning: If this device was previously added to the network, the device may need to be removed from the network and re-added.
Warning: In case the device was previously added successfully, an attempt will be made to continue the import.
Getting SECURITY class information for node 55
Error: Security class information is NOT present - cannot continue loading node 55
Finished."_

I was hoping to see a lot of devices created in Homey but none off my z-wave devices where created.

Unfortunately it fails on a security negotiation.

Is this feature currently not active in Homey fimware 0.9.3?
I succesfully included a vera edge and a domoticz server to my Homeseer as a secondary controller and i can see my z-wave device there interfaces.
But with Homey I can't see any devices created. And i can't manually add them.

**Comment by WeeJeWel** [comment]
Hm that should work. I'll look into it asap!

Please note that when Homey is added as a secondary controller, it basically cannot do anything.

**Comment by sebohans** [comment]
But it can read the z-wave sensors right? So i can make triggers based on motion sensors or light sensors?

**Comment by henkbb36org** [comment]
Adding Homey as a secondary controller (scene controller) has worked prior to 0.93. Adding Homey as a secondary controller to Vera Lite resulted in all zwave devices from Vera becoming available in Homey. However, since 0.93 devices don't become available anymore and on Vera Lite the message "Please wait! Getting the manufacturer..." appears.

**Comment by WeeJeWel** [comment]
Including should work, so if that doesn't, it's a bug. It is unsupported to control other devices when in another network as of Homey 0.9.0.

**Comment by bvdbos** [comment]
unsupported? As in : It won't be coming back as of 0.9.x and further?

**Comment by henkbb36org** [comment]
The inclusion process is finished but there is no functionality and only the message "Please wait! Getting the manufacturer..." appears in the Vera UI. Before, Vera would add Homey as a scene controller thus allowing Homey to control scenes and devices in the Vera network. What do you mean by "unsupported"? You mean it will not work that way anymore or it will work but will work but will not be supported by the  Athom.

**Comment by WeeJeWel** [comment]
It's not on our to-do list to make Homey functional as a secondary controller.

What kind of features would you want when Homey is a scene controller?

**Comment by henkbb36org** [comment]
OK I understand. It was very convenient the way it worked before; most vera z-wave devices appeared in homey after inclusion and could be used in scenes. This method is practical as long as not all (zwave) devices are working well using homey (e.g. Danfoss LC 13).

**Comment by Inversion-NL** [comment]
I would like to add Homey as a secondary controller, then transfer the network configuration to this controller, and finally make it the primary controller.
Since this didn't work and I have only a few devices I excluded all devices and included them manually to Homey.

**Comment by WeeJeWel** [comment]
Alright, I get that. However, with our approach of device-specific support using apps, that's a very difficult problem to solve, so that's why we've chosen to let Homey behave the way it does now. :)

**Comment by chusrvlim** [comment]
I have 55 z-wave devices, which makes the transition to homey a nightmare.
Are there any plans to support homey as secondary controller, replication of the network config and transferring primary controller role?

**Comment by WeeJeWel** [comment]
I've verified and I can include Homey in the 'official' Z-Wave Controller using Security. So maybe Homeseer does something... odd?

**Comment by WeeJeWel** [comment]
I've fixed a bug that causes some scenarios where Security is enabled to fail. (When the Manufacturer says that the SECURITY command class is also secure, which is not true, but somehow logical to say). Try again in 0.10.6!

**Comment by LuucE** [comment]
I tried to include as secondary controller today, with v1.0.1 in Homeseer. Secure is not possible and unsecure adding results in this message:
nov-19 15:28:58 	  	Z-Wave 	Node 39 is a Z-Wave Plus node. Retrieving ZWPlus Info...
nov-19 15:28:58 	  	Z-Wave Warning 	Error getting version information for node 39, Send failed.

**Comment by LuucE** [comment]
and this: 
nov-19 15:28:34 	  	Z-Wave Warning 	Node 39 supports the MANUFACTURER_SPECIFIC command class but manufacturer information was not obtained. Cannot continue with this node.

**Comment by niels-vdw** [comment]
I think that Homey beimg able to be a secondary controller is essential. Due to the complexity of my zwave system (Indigo) and  integration with my security system is unthinkable Homey will be the primary controller. I think a lot of serious tech/domo guys think the same. If you dont include the secondary controller option, Homey will remain a nice gadget for starters.

**Comment by qwerk** [comment]
with 1.0.3 Homey is still not able to act as a secondary controller. (domoticz with razberry)
it can be added, but not recognizable and not functional.

**Comment by WeeJeWel** [comment]
What do you expect Homey to do as a secondary controller, actually? We will not support controlling devices when Homey is a secondary controller, because of our app-based nature (this would be very, very much work for a very, very small group of people).

**Comment by qwerk** [comment]
At the moment I have 44 z-wave devices, It would eventually make the transition easier.
But for now, Domoticz is my main home-automation. But I would like to let Homey make use of sensors and turn light on and off directly without the use off web-urls (json calls)
This way I can make flow by flow working

**Comment by niels-vdw** [comment]
I like it to control devices like any other secondary controller (like remotes). There is no way I am transfering to Homey as a primary due tonthe complexity of my current system. I think many z wave user think the same.

**Comment by LuucE** [comment]
Homey is for me an extension of my primary Home automation system (Homeseer). Homey combines speak, infrared (IR) and some more sensors that are very nice if I can use them in my primary HS3 system.

**Comment by nattlip** [comment]
@Luuce  you can if you write a plugin for hs3 and app for Homey , HS3 understands json messages over the net. and Homey to.
