### ISSUE TITLE
Somfy not working on 0.10

### ISSUE THREAD

**Issue by jeroenbos22** [athombv/homey#912]
**What is your Homey version (Settings → System)?**

0.10.0

**What did you try to achieve?**

move Somfy curtains

**What was the result?**

Curtains not responding

**What did you expect as result?**

Fireworks 🎉

**Any other remarks**

Nope

**Comment by BasKiers** [comment]
Hi,

I am unable to reproduce your issue since our somfy blinds do not function anymore. The app does not crash and there were no changes in the rf library in 0.10.0.

We are aware of the problems with somfy. Most of the problems are caused by somfy having a slightly different frequency than Homey. There is a fix proposed but requires an update in the api which is not yet scheduled. When this update is rolled out I will immediately rewrite the somfy app but until then there is not much I can do.

Regards,
Bas

**Comment by jeroenbos22** [comment]
Dear Bas,

On 0.9.x Somfy worked great, no problems what so ever. On the new 0.10.0 firmware curtains are not moving. The app is not crashing, they just won't move. Not responding to any button (up, down or my).

And if I look at Slack i'm not alone reporting this issue... 

Hope it can be reproduced somehow.

Regards, Jeroen

**Comment by jeroenbos22** [comment]
It now crashes when I restart the app! I disabled it and enabled again... 
![schermafbeelding 2016-09-27 om 22 44 37](https://cloud.githubusercontent.com/assets/19820589/18891102/1a236c58-8504-11e6-99bf-a79375031c78.png)

**Comment by jeroenbos22** [comment]
Stacktrace doesn't provide many clues
![schermafbeelding 2016-09-27 om 22 46 01](https://cloud.githubusercontent.com/assets/19820589/18891135/3bf557c4-8504-11e6-87f2-aa615a3450dd.png)

**Comment by BasKiers** [comment]
Ah, your issue is related to #900. we are working on finding out what causes some apps to fail booting since we are not able to reproduce this issue.

**Comment by Inversion-NL** [comment]
Somfy works as expected at my house.
3 blinds.
Just a heads up

**Comment by bvdbos** [comment]
@jeroenbos22 This indeed looks the same like the KaKu issues (among others) I have. Suspicion is that these are devices which should have been re-paired after the last big KaKu update. Perhaps the same is the case for you?

**Comment by Inversion-NL** [comment]
I did not re-pair my Somfy devices since I have Homey in month 4 this year.
Or isn't that what you're saying

**Comment by bvdbos** [comment]
Yep, that's it. You could try to delete one of them and pair it again...

**Comment by homdom** [comment]
My problem was solved by unplug homey and plug in again. Also the kaku now works again. Reboot was not enough.

**Comment by laurenssss** [comment]
For me the repairing Helps for a few hours, then the devices can not be controlled anymore until late again repairing

**Comment by laurenssss** [comment]
Ptp also didn't do the trick

**Comment by magtimmermans** [comment]
Somfy died also in 0.10.1 :( For me it worked in 0.10

Stack trace:  
false 
Exit code: 0

**Comment by Inversion-NL** [comment]
No crashes on the app but my devices aren't working anymore.
Reboot and PTP didn't solve it.

**Comment by thezahir1** [comment]
@BasKiers Since 0.10.x Somfy gives issues for me. When installing a shutter/screen, it works and the shutter follows my up/down command from 'devices' in Homey.
But when being triggered by a flow, it won't move at all. Before 0.10.x everything worked fine.

**Comment by bvdbos** [comment]
The error with the strange Stack trace might be solved by disabling the app, leave it disabled for 60 seconds and then re-enable it.

**Comment by magtimmermans** [comment]
for me only a hard reset helped.

**Comment by Inversion-NL** [comment]
I did notice: I have some, not original (imitation), Somfy roller shutters (rolluiken), and I'm still able to control them.
The genuine Somfy roller shutter isn't working since 0.10.x

**Comment by jeroenbos22** [comment]
Re-pairing or a PTP only helps for some time. Somfy curtains again not working. :(

**Comment by bvdbos** [comment]
@jeroenbos22 Does this happen even when there haven't been any commands send to your shutters? So, is it a time-cause or a usage-cause ?

**Comment by laurenssss** [comment]
@bvdbos for me I think it is a time-cause, as I notice it is running OK for a day or so and after that I can not control them anymore
reboot or reset of chip doesn´t help.
if you want access to my homey to troubleshoot let me know, no problem

**Comment by thezahir1** [comment]
Same here, as @laurenssss .

**Comment by JPe2** [comment]
For me Somfy controling via Flow doesn't work anymore since Homey V0.10.? 
I have now V0.10.2 and it's not working. 
Screen control via App or via Device does work O.K.  Via Flow Test not :
![image](https://cloud.githubusercontent.com/assets/3833862/19081684/796a4374-8a5b-11e6-8b14-2d90ce5da63c.png)
The speak command works (see "Vinkje") but the screen doesn't go Up.

**Comment by jeroenbos22** [comment]
@bvdbos think its a time-thing allthough just update to 0.10.2 and not working at the moment (not from devices or flow)

**Comment by magtimmermans** [comment]
for me, this was working again after a full reset!

**Comment by laurenssss** [comment]
here after the first full reset it was working, second it was not anymore.....

**Comment by laurenssss** [comment]
shared the following with Bas via slack......

very strange behaviour, some of the curtains are working here (1st floor) and some are not (ground floor), both did work in the past (pre 0.10.x), both can be added succesfully currently and confirm to that (short going up and down), but only the 1st floor ones respond to commands from homey

**Comment by JPe2** [comment]
@laurenssss   there is a difference in commands, 
÷ opening and closing via the devices-tab and via the App on smartphone
÷ controling via flows
In my case (homey v0.10.3) the first option works, the second (via flows) doesn't work.
How is this in your case?

**Comment by laurenssss** [comment]
@JPe2 for me the 1st works for the upstairs curtains, not for the downstairs
2nd haven´t tried with upstairs, but is not working for downstairs

**Comment by thezahir1** [comment]
Not true here @JPe2.... Even controlling it via devices or mobile app stops working after a certain time (few days after repairing it).

**Comment by JPe2** [comment]
@thezahir1   Homey v0.10.3 exist onley 1 day!?

**Comment by thezahir1** [comment]
Not true @JPe2, was released the 4th Oct. (https://forum.athom.com/discussion/2007/homey-v0-10-3)

**Comment by JPe2** [comment]
@thezahir1  you'r right, sorry, it was on my system i updated 1 day ago, up till now direct commands still work, lets wait and see if it keeps working several days.

**Comment by jordenc** [comment]
I am having problems with pairing in 0.10.3 with the latest Somfy software version installed on Homey.
I added it as a window covering. Hold the button on the back of the remote until the window covering moves. I press next, then Homey moves the window covering (down an inch, then up and inch, like when I pressed the back button on the remote). Which seems to me that Homey does recognize and replicate the signal correctly.

However, there is no "Next" or "Add" button in the screen:
<img width="575" alt="schermafbeelding 2016-10-09 om 13 36 07" src="https://cloud.githubusercontent.com/assets/17727803/19220114/b369d65c-8e25-11e6-85de-1da73daa8676.png">

**Comment by magtimmermans** [comment]
For me pairing works, most of the time. But after a few hours the device won't work anymore. I really hope this will be in 0.10.4 fixed as this is very annoying.

**Comment by thezahir1** [comment]
Was this issue tackled in 0.10.5 @BasKiers ?

**Comment by magtimmermans** [comment]
In 0.10.5 -> same issue :) not working

**Comment by jeroenbos22** [comment]
With the last app-update it works again for me, no problems since! ❤️

**Comment by jordenc** [comment]
Same here, with 0.10.5 and the latest app version I now have no problems pairing. No missing buttons either <3

**Comment by jaxc0402** [comment]
For me also Somfy still not working, Pairing seems to work, the roller shutters go up and down. But after that .... Nothing.... Firmware 0.10.7 ... any news on this?? Prior to 0.10 all worked OK

**Comment by edtst** [comment]
0.10.9 still not working.

**Comment by Inversion-NL** [comment]
For what it's worth: still working flawless at my place.

**Comment by mruiter** [comment]
Can also confirm it has been working rock solid for more then 30 meters and 3 wall since 0.9 something. Did not have a single failure or misfire

**Comment by glijie** [comment]
Here have 4 roller-blinds working with somfy motors.2 working on 220 V and 2 working on batteries.
the 2 somfy motors which are working on 220V are working great!!

the other 2 which work on batteries are just working for 2 sec. after that i have to give another signal to move and then the roller-blind moves again for 2 sec....and so on.

this has been from the early somfy app versions

**Comment by edtst** [comment]
What is the status? Still not working in 101?

**Comment by bvdbos** [comment]
https://forum.athom.com/discussion/2080/kaku-remember-devices-have-only-6-memory-places-some-get-wasted-after-deleting-devices-or-setup
Perhaps a full reset of Somfy works?

**Comment by magtimmermans** [comment]
Yes, this works (most of the time) but after a few days/weeks it stops working again. Even after ptp.

**Comment by edtst** [comment]
This is exactly my experience  When it works, it works fine, but then it stops and you have to reinstall and re-pair.

**Comment by BasKiers** [comment]
Hi, 

As you will probably have noticed the Somfy app is updated and now uses a new driver (as of v2.0.0). I think the bug where Somfy blinds would work for a couple of weeks and then stopped should be fixed with this update. If you still experience problems pairing please try to reset your somfy blinds because the issue could be that the memory of the blinds is full. More info on this can be found [here](https://www.blindschalet.com/pdfs/Installation/programming-rts-motors.pdf) or in the manual of your device. If this does not fix your issues please comment below or open a new issue.

Regards,
Bas

**Comment by glijie** [comment]
never had the issue that somfy stopt working, 
only that some of mine blinds worked for 2 sec.  This issue still exists exept when i choose the longer signal. Then the blinds go up or down for about 4 seconds.

As i early wrote, this issue only exists for 2 blinds ( i have 4 blinds)

PS: No problems pairing

**Comment by BasKiers** [comment]
@glijie When you operate those blinds with the remote do you have to hold the button for the blinds to go up or down?

**Comment by glijie** [comment]
no have to press just once

**Comment by BasKiers** [comment]
Hmm very strange that they do work but they will stop once no signal is send by the remote, could you share what model remote/blinds you have?

**Comment by glijie** [comment]
![20161124_085505](https://cloud.githubusercontent.com/assets/19786633/20590865/e49aac46-b225-11e6-962d-df1e4714e96a.jpg)
![20161124_085410](https://cloud.githubusercontent.com/assets/19786633/20590844/d2241e30-b225-11e6-9ba5-c1c146d43f79.jpg)
![20161124_085454](https://cloud.githubusercontent.com/assets/19786633/20590850/d60ad4c6-b225-11e6-8bcd-9d789056b880.jpg)

**Comment by evenhuizen** [comment]
Is there a fix or progress on the issue mentioned by glijie? I also have the issue that my blinds go up or down for only 2 sec. I use the battery/solar powered RTS.

**Comment by BasKiers** [comment]
No not at the moment since I do not have a shutter that has this problem at the office. Could you confirm that the blinds do work longer when the "long signal" options in the device settings is turned on?

**Comment by glijie** [comment]
yes they work longer over here.

**Comment by evenhuizen** [comment]
Yes 4 sec instead of 2 sec.

**Comment by evenhuizen** [comment]
I just tested when they are connected to the 230v and I encounter the same behavior. 2 sec down and 4 when long signal is selected.

**Comment by BasKiers** [comment]
Hi,

Thanks for testing. I find it strange that the homewizard does not have this issue. One thing that could cause it is if the signal is too long and the blinds are programmed to stop when a button is held or something. Could you check if holding the button on the remote or pressing the button a second time after the blinds begin to move result in similar behavior?

Regards,
Bas

**Comment by glijie** [comment]
@BasKiers 

If i hold the up or down button from the remote for a longer time then the blinds move if i release the  button of the remote the blind stop moving.
I'm sure that you'r right that the signal is to long because if i press the remote button for a long time the blind moves slower then when just pressing the remote for a short time. When send a signal thru homey by press up or down the blinds move slower

When i give short repeated signals with the remote then te blinds keep moving, they don't stop until i press the MY button on the remote. And that works good

**Comment by BasKiers** [comment]
Hi, 

Thanks for your input! I will look into updating the somfy app with a shorter (repeated) signal.

Regards,
Bas

**Comment by BasKiers** [comment]
I just updated the Somfy app and there are now 3 settings added for shorter signals. For reference, the original setting "short" setting (now called "normal") does 20 repetitions of the signal. The three shorter settings have 5, 10 and 15 repetitions. Could you check which of the signals work like expected? Also, @evenhuizen could you try executing the flow card 4 times to achieve the same result as clicking the remote 4 times?

Regards,
Bas

**Comment by glijie** [comment]
@BasKiers 
There is some improvement the MY button works now also in the somfy app!!! great!! I can move the blinds to the favorite position to press stop button in the app, and i can stop the blinds to press the stop button when blinds are moving. This has also never worked on the non batterie powered blinds. So great job on this!

Up/Down is not working ....after intensife testing it works maybe 1 of the 50 times i press. 
So did some more testing and counted the times i press on my remote and came to the conclusion that the 5 times repetitions are 1 or 2 to much if you can lower these to 3 than i'm pretty sure it will works

Thx 
Patrick

**Comment by evenhuizen** [comment]
I have less better results. I will record a video tomorrow and include the homey flow settings or results from the app.

**Comment by glijie** [comment]
@BasKiers 
If you find some time to change for the shortest signals the repetitions from 5 to 3 than maybe ik can finaly turn off mine homewizard.

thx

Patrick

**Comment by JPe2** [comment]
Maybe it would be bëtter to make this value setable to any value from one to 50, so every one can choose what is the best value for him.

**Comment by glijie** [comment]
would be nice if the changes coult be done today:-/

**Comment by BasKiers** [comment]
Just updated the somfy app to 2.1.11 which changed the short signals to 2/3/4 repetitions. Could you try again with these settings? Unfortunately it is not possible to let a user enter the amount of repetitions manually since this value is stored in the config file of the app and cannot be changed while running the app.

**Comment by glijie** [comment]
Thx for the Update, Did today a full factory reset of mine somfy's and removed my flows before I deleted the APP, SO i could start over from scratch.
After reinstalled the APP there was no difference.

The signals wich are send are to long. The somfy moves as of I keep pressed the UP or DOWN Button

So the Signals repetition could be okay Because the somfy moves But the Signals which are send are To long for my battery powered somfy's

For my none battery powered somfy's there is no difference, they keep working as supposed:-)

patrick

**Comment by glijie** [comment]
**Bump**

**Comment by Inversion-NL** [comment]
I'm also unable to add my Somfy roller shutters.
They were working great until I had to readd them

**Comment by BasKiers** [comment]
@Inversion-NL It could be that the memory of your somfy roller shutters is full. You can fix this issue by resetting the roller blinds, instructions can be found in the manual or this information sheet: https://www.blindschalet.com/pdfs/Installation/programming-rts-motors.pdf

**Comment by BasKiers** [comment]
Hi,

Sorry, I did not have time or the resources to further debug this issue. I think the next step is for us to buy the same hardware you have to try and duplicate the issue. For what it is worth I did update the app to send 1/2/4 repetitions so you could try setting it to 1 repetition to check if that fixes the issue but I don't think it will matter. 

Could you post the exact model number of the blinds that have this behaviour?

Regards,
Bas

**Comment by glijie** [comment]
Bas,

The last update did the trick!! It works great now! UP DOWN And when I press STOP it stops :-)
When I start pushing STOP the blinds go to the favorite setting.

great Job

THANKS Bas

regards 
Patrick
