### ISSUE TITLE
Changing brightness on Philips Hue lights does not work

### ISSUE THREAD

**Issue by MdeRhoter** [athombv/homey#913]
On 0.10.0 with Hue 1.0.5, changing the brightness of a Hue light does not work. When testing the flow, the first card gets stuck on the spinning circle:

![image](https://cloud.githubusercontent.com/assets/15713184/18888937/d41b1638-84fa-11e6-9192-93fbed71579c.png)

Removing that card with the circle (to check for a faulty lamp) does not help, the next one down will display the same issue. The only Philips Hue light that does not exhibit this behaviour is the Bloom.

Manually changing brightness using the slider on the Devices pages does work.

**Comment by Arjanvde** [comment]
Think this is solved in #893, or at least I hope

**Comment by WeeJeWel** [comment]
Indeed a duplicate of #893, it's fixed in 0.10.1

**Comment by MdeRhoter** [comment]
Alright, thanks!

**Comment by MdeRhoter** [comment]
Still an issue in 0.10.1 (although the added-delay-bug has been fixed, cards without Hue devices execute fine)

**Comment by MdeRhoter** [comment]
On 0.10.2, there's still an issue with dimming, it's just more than Philips Hue (and may be related to incorrectly actioning cards).

When these cards are executed (either through flipping the boolean variable that triggers them or by pressing Test) the lights dim and immediately revert back to their earlier value (undimmed)

![image](https://cloud.githubusercontent.com/assets/15713184/19085018/09141fd8-8a69-11e6-8164-bbca055e778f.png)

**Comment by MdeRhoter** [comment]
Looks like this is covered in https://github.com/athombv/homey/issues/934
